In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [5]:
dataset=pd.read_csv("7.1 Social_Network_Ads.csv.csv")

In [6]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
X=dataset.iloc[:,[2,3]].values

In [8]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [9]:
Y=dataset.iloc[:,[4]].values

In [10]:
Y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [11]:
from sklearn.model_selection import train_test_split


In [12]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25)

In [13]:
X_train

array([[    46,  88000],
       [    24,  32000],
       [    37,  77000],
       [    47, 105000],
       [    26,  16000],
       [    25,  87000],
       [    58, 144000],
       [    42,  53000],
       [    56, 104000],
       [    25,  33000],
       [    18,  44000],
       [    48,  74000],
       [    21,  16000],
       [    30,  49000],
       [    53,  82000],
       [    27,  54000],
       [    26,  80000],
       [    23,  20000],
       [    39, 134000],
       [    58,  38000],
       [    31,  71000],
       [    41,  72000],
       [    28,  85000],
       [    21,  68000],
       [    20,  74000],
       [    22,  55000],
       [    41,  63000],
       [    28,  59000],
       [    47,  47000],
       [    26,  52000],
       [    32,  86000],
       [    21,  88000],
       [    23,  82000],
       [    34,  25000],
       [    31,  15000],
       [    20,  82000],
       [    35,  44000],
       [    35,  72000],
       [    20,  36000],
       [    35,  47000],


In [14]:
Y_train

array([[1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [77]:
X_train.shape

(300, 2)

In [78]:
Y_train.shape

(300, 1)

In [79]:
from sklearn.preprocessing import StandardScaler

In [80]:
sc=StandardScaler()

In [81]:
X_train=sc.fit_transform(X_train)

In [82]:
X_test=sc.fit_transform(X_test)

In [83]:
X_train

array([[ 0.82085608,  0.54755933],
       [-1.25090306, -1.07483869],
       [-0.02668175,  0.22887401],
       [ 0.91502695,  1.04007301],
       [-1.06256132, -1.53838098],
       [-1.15673219,  0.51858794],
       [ 1.95090652,  2.16995735],
       [ 0.4441726 , -0.46643943],
       [ 1.76256478,  1.01110162],
       [-1.15673219, -1.04586729],
       [-1.81592827, -0.72718197],
       [ 1.00919782,  0.14195983],
       [-1.53341566, -1.53838098],
       [-0.68587784, -0.582325  ],
       [ 1.48005217,  0.37373097],
       [-0.96839045, -0.43746804],
       [-1.06256132,  0.31578819],
       [-1.34507393, -1.4224954 ],
       [ 0.16165999,  1.88024341],
       [ 1.95090652, -0.90101033],
       [-0.59170697,  0.05504565],
       [ 0.35000173,  0.08401704],
       [-0.87421958,  0.46064515],
       [-1.53341566, -0.03186853],
       [-1.62758653,  0.14195983],
       [-1.4392448 , -0.40849664],
       [ 0.35000173, -0.1767255 ],
       [-0.87421958, -0.29261107],
       [ 0.91502695,

In [84]:
from sklearn.neighbors import KNeighborsClassifier

In [85]:
Classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski')

In [86]:
Classifier.fit(X_train,Y_train)

C:\Users\venka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [87]:
Y_pred=Classifier.predict(X_test)

In [88]:
Y_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1], dtype=int64)

In [89]:
Y_test

array([[1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
    

In [90]:
from sklearn.metrics import confusion_matrix

In [91]:
cm=confusion_matrix(Y_test,Y_pred)

In [92]:
cm

array([[56,  5],
       [ 5, 34]], dtype=int64)

In [93]:
(56+34)/(56+5+5+34)

0.9

In [94]:
from sklearn.metrics import accuracy_score

In [95]:
c=accuracy_score(Y_test,Y_pred)

In [96]:
c

0.9

In [106]:
y=Classifier.predict(np.array([[-0.12085262, -0.43746804]]))

In [107]:
print(y)

[0]
