In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
%matplotlib inline

In [125]:
data = pd.read_csv("C:/Users/venka/Downloads/Datasets/diabetes.csv")


In [126]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [127]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [128]:
X=data.iloc[:,[0,1,2,3,4,5,6,7]].values

In [129]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [130]:
Y=data.iloc[:,[8]].values

In [131]:
Y

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [132]:
from sklearn.model_selection import train_test_split


In [150]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.15)

In [151]:
X_train.shape

(652, 8)

In [152]:
Y_train.shape

(652, 1)

In [153]:
from sklearn.preprocessing import StandardScaler

In [154]:
sc=StandardScaler()

In [155]:
X_train=sc.fit_transform(X_train)

In [156]:
X_test=sc.fit_transform(X_test)

In [157]:
from sklearn.neighbors import KNeighborsClassifier

In [182]:
Classifier=KNeighborsClassifier(n_neighbors=6,metric='minkowski',p=2)

In [183]:
Classifier.fit(X_train,Y_train)

C:\Users\venka\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [184]:
Y_pred=Classifier.predict(X_test)

In [185]:
Y_pred

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0], dtype=int64)

In [186]:
Y_test

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [187]:
y

array([[-0.03731514],
       [ 0.23389728],
       [ 0.51662848],
       [ 0.37383238],
       [ 0.03544976],
       [ 0.79635733],
       [ 0.18766674],
       [ 0.25536201],
       [ 0.12007706],
       [ 0.09869972],
       [ 0.07148385],
       [ 0.35479908],
       [ 0.31738365],
       [ 0.47393195],
       [ 0.14504907],
       [ 0.00456205],
       [ 0.42839256],
       [ 0.32617306],
       [ 0.74176908],
       [ 0.26779857],
       [ 0.67583314],
       [ 0.53557331],
       [ 0.23193634],
       [-0.0192869 ],
       [ 0.11794075],
       [ 0.61978362],
       [ 0.98147099],
       [ 0.20956703],
       [ 0.17015655],
       [ 0.07419564],
       [ 0.36256649],
       [-0.01567138],
       [-0.26442057],
       [ 0.24756252],
       [ 0.67208497],
       [ 0.77891253],
       [ 0.37324464],
       [ 0.61844602],
       [ 0.06380492],
       [ 0.72205737],
       [ 0.15024381],
       [ 0.28494515],
       [ 0.14220295],
       [ 0.41880697],
       [ 0.61469866],
       [ 0

In [188]:
from sklearn.metrics import accuracy_score

In [189]:
c=accuracy_score(Y_test,Y_pred)

In [190]:
c

0.7155172413793104